export const units = {
    Serge: {
        name: "Serge",
        class: "Mercenary",
        description: "Serge is cool.",
        tile: "Creator",
        imageDirectory: "./assets/units/Serge",
        move: 2,
        attack: 10,
        defense: 10,
        resistance: 10,
        speed: 10,
        skill: 10,
        luck: 10,
        hp: 10,
    },
    Mia: {
        name: "Mia",
        class: "Mage",
        description: "Mia is cool.",
        tile: "Creator's Wife",
        imageDirectory: "./assets/units/Mia",
        move: 3,
        attack: 10,
        defense: 10,
        resistance: 10,
        speed: 10,
        skill: 10,
        luck: 10,
        hp: 10,
    },
    Jim: {
        name: "Jim",
        class: "Knight",
        description: "Jim is cool.",
        tile: "Bad Guy",
        imageDirectory: "./assets/units/Jim",
        move: 1,
        attack: 10,
        defense: 10,
        resistance: 10,
        speed: 10,
        skill: 10,
        luck: 10,
        hp: 15,
    },
};